name: Deployment Pipeline

on: 
  push:
    - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install dependenies
        run : npm install
      - name : Lint
        run : npm run eslint