name: Deployment Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:

  avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
      # Para cancelar dos build en paralelo tests d
      - name: Cancel Previous Redundants builds
        uses: styfle/cancel-workflow-action
        with:
          access_token: ${{github.token}} 
  lint: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies --no-audit --no-fund --no-optional
        run: npm ci
      - name: Eslint
        run: npm run eslint
  
  build: 
    runs-on: ubuntu-20.04
    steps:   

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies --no-audit --no-fund --no-optional
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  
  tests: 
    needs: [lint, build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies --no-audit --no-fund --no-optional
        run: npm ci
      - uses: actions/dowload-artifact@v3
        with:
          name: dist
          path: dist
      - name: Test
        run: npm run test

  e2e:
    needs: [lint, build]
    runs-on: ubuntu-20.04
    steps:    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Install dependencies --no-audit --no-fund --no-optional
      run: npm ci
    - uses: actions/dowload-artifact@v3
      with:
        name: dist
        path: dist
    - name: E2E tests
      uses: cypress-io/github-action@v4
      with:
        command: npm run test:e2e
        start: npm run start-test
        wait-on: http://localhost:3001


  deploy:
    needs: [tests, e2e]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0      
          # Deploy in heroku
      - name: Deploy to Heroku
        if: ${{ github.event_name =='push'}}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
#  /c/xampp/htdocs/pokedex-for-ci
# Token
#  1eb563e8-40b0-4605-9cd1-20856c453b44
